Repository dirien/minecraft-prometheus-exporter, pull requests merged in 2022-01, with the labels that each got.

#71 feat: add environment variable support for flags
  README.md
  pkg/config/config.go
Labels: size/M

#77 feat: add namespace label to certain metrics.
  README.md
  pkg/exporter/exporter.go
Labels: size/L

#84 feat: add docker manifest support
  .goreleaser.yaml
Labels: size/S

#85 feat: Disabling collection of exporter metrics (like go_*)
  .gitignore
  README.md
  cmd/minecraftExporter/main.go
  pkg/config/config.go
Labels: size/L

#86 fix: error in goreleaser docker_manifests tag
  .goreleaser.yaml
Labels: size/XS

#87 fix: error in goreleaser docker_manifests tag
  .goreleaser.yaml
Labels: size/S

#89 feat: add Helm chart
  .github/workflows/helm-publish.yaml
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  README.md
  chart/.helmignore
  chart/Chart.yaml
  chart/README.md.gotmpl
  chart/templates/NOTES.txt
  chart/templates/_helpers.tpl
  chart/templates/deployment.yaml
  chart/templates/podsecuritypolicy.yaml
  chart/templates/role.yaml
  chart/templates/rolebinding.yaml
  chart/templates/service.yaml
  chart/templates/serviceaccount.yaml
  chart/templates/servicemonitor.yaml
  chart/values.yaml
  git-hook/helm-docs.sh
Labels: size/XL

#91 fix: rewrite env variable access
  .github/workflows/helm-publish.yaml
Labels: size/XS

#92 fix: rewrite env variable access
  .github/workflows/helm-publish.yaml
Labels: size/XS

#93 fix: separate install from run helm-docs
  .github/workflows/helm-publish.yaml
Labels: size/XS

#94 fix: add chart testing and linting
  .github/configs/ct-lint.yaml
  .github/configs/lintconf.yaml
  .github/workflows/ci.yaml
  .github/workflows/helm-publish.yaml
  .github/workflows/lint-and-test.yml
  .gitignore
  charts/minecraft-exporter/.helmignore
  charts/minecraft-exporter/Chart.yaml
  charts/minecraft-exporter/README.md
  charts/minecraft-exporter/README.md.gotmpl
  charts/minecraft-exporter/templates/NOTES.txt
  charts/minecraft-exporter/templates/_helpers.tpl
  charts/minecraft-exporter/templates/deployment.yaml
  charts/minecraft-exporter/templates/podsecuritypolicy.yaml
  charts/minecraft-exporter/templates/role.yaml
  charts/minecraft-exporter/templates/rolebinding.yaml
  charts/minecraft-exporter/templates/service.yaml
  charts/minecraft-exporter/templates/serviceaccount.yaml
  charts/minecraft-exporter/templates/servicemonitor.yaml
  charts/minecraft-exporter/values.yaml
Labels: size/L

#95 feat: add chart release
  .github/configs/cr.yaml
  .github/workflows/helm-publish.yaml
  charts/minecraft-exporter/Chart.yaml
  charts/minecraft-exporter/README.md
Labels: size/S

#96 feat: add usage and graphic
  README.md
  charts/minecraft-exporter/Chart.yaml
  charts/minecraft-exporter/README.md
  charts/minecraft-exporter/README.md.gotmpl
Labels: size/M

#97 feat: add chart logo
  charts/minecraft-exporter/Chart.yaml
Labels: size/XS

#98 feat: add ArtifactHub badge
  README.md
  charts/minecraft-exporter/Chart.yaml
  charts/minecraft-exporter/README.md
  charts/minecraft-exporter/README.md.gotmpl
Labels: size/S

#82 fix: typos and inconsistencies in metric descriptions
  README.md
  pkg/exporter/exporter.go
Labels: size/L

#99 docs: add CONTRIBUTING.md, DCO and SECURITY.md
  CONTRIBUTING.md
  DCO
  SECURITY.md
Labels: size/L

#81 fix: minecraft_play_time_ticks_total
  pkg/exporter/exporter.go
Labels: size/XS

#100 chore: update appversion to v0.10.0
  charts/minecraft-exporter/Chart.yaml
Labels: size/S

#101 feat: add overall TPS, Ticktime and entity stats for Forge servers
  README.md
  cmd/minecraftExporter/main.go
  pkg/config/config.go
  pkg/exporter/exporter.go
Labels: size/L

#102 chore: update version of container to 0.11.0
  charts/minecraft-exporter/Chart.yaml
  charts/minecraft-exporter/README.md
Labels: size/XS

#107 feat: prepare minecraft-exporter image to upload into ArtifactHub
  .github/configs/cr.yaml
  .goreleaser.yaml
Labels: size/M

#108 feat: prepare minecraft-exporter image to upload into ArtifactHub
  .goreleaser.yaml
Labels: size/M

#109 feat: refine minecraft-exporter image in ArtifactHub
  .goreleaser.yaml
  CONTAINER.md
  README.md
  charts/minecraft-exporter/Chart.yaml
  charts/minecraft-exporter/README.md.gotmpl
Labels: size/M

#110 chore: update helm chart to AppVersion 0.11.2
  .github/configs/cr.yaml
  .github/workflows/helm-publish.yaml
  charts/minecraft-exporter/Chart.yaml
Labels: size/S

#116 fix: fix the permissions of the pipelines
  .github/workflows/ci.yaml
  .github/workflows/helm-publish.yaml
Labels: size/S

#129 feat: fix actions with renovate annotation
  .github/workflows/ci.yaml
  .github/workflows/helm-publish.yaml
  .github/workflows/lint-and-test.yml
  .github/workflows/lint.yaml
  .github/workflows/ossf-scorecard-action.yaml
Labels: size/M
