Repository dirien/minecraft-prometheus-exporter, pull requests merged in 2024-09, with the labels that each got.

#999 chore: update chart
  charts/minecraft-exporter/Chart.yaml
  charts/minecraft-exporter/README.md
Labels: size/S

#958 [main] adds fabric support
  CONTAINER.md
  README.md
  pkg/config/config.go
  pkg/exporter/exporter.go
Labels: size/M

#929 [main] fixes broken spaces logic
  pkg/exporter/exporter.go
Labels: size/XS

#1000 feat: rewrite if-else to switch statement
  pkg/exporter/exporter.go
Labels: size/S

#1001 chore: update helm chart for latest release
  charts/minecraft-exporter/Chart.yaml
  charts/minecraft-exporter/README.md
Labels: size/S
